/** Tipos de efectos de poción disponibles en el generador. */
export const EFFECT_TYPES = [
  { label: 'Velocidad',            value: 'speed',           color: 'text-sky-300' },
  { label: 'Lentitud',             value: 'slowness',        color: 'text-slate-400' },
  { label: 'Fuerza',               value: 'strength',        color: 'text-rose-400' },
  { label: 'Regeneración',         value: 'regeneration',    color: 'text-pink-400' },
  { label: 'Veneno',               value: 'poison',          color: 'text-lime-400' },
  { label: 'Wither',               value: 'wither',          color: 'text-neutral-400' },
  { label: 'Resistencia al fuego', value: 'fire_resistance', color: 'text-orange-400' },
  { label: 'Caída lenta',          value: 'slow_falling',    color: 'text-blue-300' },
  { label: 'Resistencia',          value: 'resistance',      color: 'text-amber-500' },
  { label: 'Invisibilidad',        value: 'invisibility',    color: 'text-slate-300' },
  { label: 'Visión nocturna',      value: 'night_vision',    color: 'text-indigo-300' },
  { label: 'Salto mejorado',       value: 'jump_boost',      color: 'text-yellow-300' },
  { label: 'Hambre',               value: 'hunger',          color: 'text-amber-700' },
  { label: 'Náuseas',              value: 'nausea',          color: 'text-green-500' },
  { label: 'Oscuridad',            value: 'darkness',        color: 'text-zinc-500' },
  { label: 'Fatiga minera',        value: 'mining_fatigue',  color: 'text-yellow-700' },
  { label: 'Prisa',                value: 'haste',           color: 'text-amber-400' },
  { label: 'Daño instantáneo',     value: 'instant_damage',  color: 'text-red-800' },
  { label: 'Vida instantánea',     value: 'instant_health',  color: 'text-red-500' },
  { label: 'Brillo',               value: 'glowing',         color: 'text-emerald-300' },
  { label: 'Levitación',           value: 'levitation',      color: 'text-cyan-300' },
  { label: 'Gracia de delfín',     value: 'dolphins_grace',  color: 'text-blue-400' },
  { label: 'Velocidad de almas',   value: 'speed',           color: 'text-teal-300' },
  { label: 'Debilidad',            value: 'weakness',        color: 'text-gray-400' },
]
