/** IDs de ítems vanilla de Minecraft disponibles para usar en recetas. */
export const MINECRAFT_ITEMS = [
  'minecraft:stick',
  'minecraft:iron_ingot',
  'minecraft:gold_ingot',
  'minecraft:diamond',
  'minecraft:netherite_ingot',
  'minecraft:oak_planks',
  'minecraft:oak_log',
  'minecraft:cobblestone',
  'minecraft:stone',
  'minecraft:coal',
  'minecraft:redstone',
  'minecraft:lapis_lazuli',
  'minecraft:emerald',
  'minecraft:copper_ingot',
  'minecraft:string',
  'minecraft:feather',
  'minecraft:flint',
  'minecraft:leather',
  'minecraft:blaze_rod',
  'minecraft:ender_pearl',
  'minecraft:obsidian',
  'minecraft:glass_pane',
  'minecraft:iron_block',
  'minecraft:gold_block',
  'minecraft:diamond_block',
]
